apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vault
  labels:
    app: nginx-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vault
  template:
    metadata:
      labels:
        app: nginx-vault
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "taha"
        vault.hashicorp.com/agent-inject-secret-mysecret: "secret/data/taha/config"
        vault.hashicorp.com/agent-inject-template-mysecrets: |
          {{- with secret "secret/data/taha/config" -}}
          {{- range $key, $value := .Data.data }}
          export {{ $key | toUpper }}="{{ $value }}"
          {{- end }}
          {{- end }}

    spec:
      serviceAccountName: taha
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taha
  labels:
    app: nginx-vault
