apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vault
  labels:
    app: nginx-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vault
  template:
    metadata:
      labels:
        app: nginx-vault
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "taha"
        vault.hashicorp.com/agent-inject-secret-mysecret: "secret/data/taha/config"
        vault.hashicorp.com/agent-inject-template-mysecret: |
          {{- with secret "secret/data/taha/config" -}}
          export API_KEY="{{ .Data.data.api_key }}"
          export API_SECRET="{{ .Data.data.api_secret }}"
          {{- end -}}
    spec:
      serviceAccountName: taha
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
        - |
          #!/bin/sh
          . /vault/secrets/mysecret
